version: '3.7'

services:

  postgres:
    image: postgres
    volumes:
      - ./dockerfiles/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/dockerfiles/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
      container_name: backend
      build:
        context: ./backend
        dockerfile: Dockerfile
      volumes:
        - '.:/app'

      ports:
        - 8000:8000
      depends_on:
        - postgres
