version: '3.7'

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/dockerfiles/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
      container_name: backend
      build:
        context: ./backend
        dockerfile: Dockerfile
      volumes:
        - '.:/app'
      ports:
        - 5000:5000

